### ISSUE TITLE
Enhancement - Show status of variable speed pump

### ISSUE THREAD

**Issue by richardmarr** [michaelpettorosso/homebridge-connect-my-pool-home-automation#2]
I have a variable speed pump for my pool system.

The current view in homekit just shows whether the pump is on or off, not the status/speed.

Would be amazing! if we could see speed/status?

Also would love to see PH and ORP level of water chemistry as well since I am asking ;)

See images below - love your app! thanks so much!

![IMG_4240](https://github.com/michaelpettorosso/homebridge-connect-my-pool-home-automation/assets/26127892/0ebc5fa9-a27a-45c8-853f-2e8166e6538c)
![IMG_4244](https://github.com/michaelpettorosso/homebridge-connect-my-pool-home-automation/assets/26127892/b2973dbd-9acf-4040-ba86-33d7b6000d34)
![IMG_4241](https://github.com/michaelpettorosso/homebridge-connect-my-pool-home-automation/assets/26127892/1ce56d36-e2cf-4280-ada8-08007a658511)
![IMG_4242](https://github.com/michaelpettorosso/homebridge-connect-my-pool-home-automation/assets/26127892/8a48efb1-d890-434e-9328-6bb456ea07ec)
![IMG_4243](https://github.com/michaelpettorosso/homebridge-connect-my-pool-home-automation/assets/26127892/4e7f6956-70b2-4615-87dc-7878ec8b3d4f)
![IMG_4245](https://github.com/michaelpettorosso/homebridge-connect-my-pool-home-automation/assets/26127892/af3695ee-cc38-42e7-bdca-1bf7d330e60b)

**Comment by michaelpettorosso** [comment]
The API doesn’t provide ORP or Chemistry information unfortunately, I’d love that info as well.HomeKit doesn’t have any device (switch or whatever) yet to represent state, when that changes I’ll make a change. I also have a variable pump system and that information would be so helpful. Sent from my iPadOn 20 Jan 2024, at 07:47, richardmarr ***@***.***> wrote:﻿
I have a variable speed pump for my pool system.
The current view in homekit just shows whether the pump is on or off, not the status/speed.
Would be amazing! if we could see speed/status?
Also would love to see PH and ORP level of water chemistry as well since I am asking ;)
See images below - love your app! thanks so much!
IMG_4240.PNG (view on web)
IMG_4244.PNG (view on web)
IMG_4241.PNG (view on web)
IMG_4242.PNG (view on web)
IMG_4243.PNG (view on web)
IMG_4245.PNG (view on web)

**Comment by richardmarr** [comment]
Thanks so much

**Comment by richardmarr** [comment]
Hopefully HomeKit will provide this soon
